### ISSUE TITLE
Set-GAUser OrgUnitPath Parameter

### ISSUE THREAD

**Issue by robcerda60** [squid808/gShell#33] opened 2016-10-17 15:43 UTC
Getting the following error when specifying a new orgunitpath 

Parameter set cannot be resolved using the specified named parameters.

**Comment by squid808** [comment] 2016-12-07 06:36
This seems to be resolved in the next release. For example:
```set-gauser "UserName" -OrgUnitPath "/SomeOrgUnit" -GAuthId "domain.com"```

Where ```GAuthId``` is the replacement for what used to be ```Domain```, this works without issue. Just don't forget to include the preceeding ```/``` otherwise you'll get an error. Please give that a try on the next release and let me know if you still run in to issues. Or, if you want to provide an example line for me to try and reproduce the issue, I'll be happy to give it a run.

I'll close this once the next release is out.

**Comment by squid808** [comment] 2016-12-27 07:00
You can find a [pre-release of version 0.10.0 on the downloads page](https://github.com/squid808/gShell/wiki/Downloads), with [information on the beta release on the news page](https://github.com/squid808/gShell/wiki/News). Please read up on the breaking changes mentioned, and test it out to see if you are having any issues.

Over the next month or so I'll work to fix any remaining issues and then switch it to a full release.

Thanks!

**Closed** 2017-02-03 03:38 UTC
Labels: question
