### ISSUE TITLE
Load module issue

### ISSUE THREAD

**Issue by EwanSadie** [squid808/gShell#10] opened 2016-01-26 13:08 UTC
I have installed 0.0.8.1 using the MSI.  I get the below error on Windows 10 but not on Windows 7.
I have also configured the API's but do not know where to place the JSON files.
All dll files are in C:\Users\xxxxxx\Documents\WindowsPowerShell\Modules\gShell

PS C:\WINDOWS\system32> Import-Module gShell
Import-Module : Could not load file or assembly 'Google.Apis.Admin.Directory.directory_v1, Version=1.9.0.49, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The
system cannot find the file specified.
At line:1 char:1
+ Import-Module gShell
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by squid808** [comment] 2016-01-26 14:14
Crap, I'm sorry about that - that was supposed to be what was fixed in x8.1. I'll double check things on my end, when I tested it yesterday it seemed like the issue was resolved. Can you check in your *\Documents\WindowsPowerShell\Modules\gShell* folder and see if you have a file called **Google.Apis.Admin.Directory.directory_v1.dll**?

Also, did you upgrade gShell, or did you do a fresh install? If you upgraded, try quickly uninstalling, making sure the above folder is empty, and reinstalling. I'll try to get this working for you ASAP.

**Comment by EwanSadie** [comment] 2016-01-26 14:54
Thanks for the reply.
I did a new install.

The DLL is there.

	Ewan Sadie
Retail IT
Metropolitan

Tel: +27219405300
Parc du Cap, Mispel Road, Bellville, 7535
Cape Town

www.metropolitan.co.za <http://www.metropolitan.co.za>

**Comment by squid808** [comment] 2016-01-26 14:57
Thanks for the update - just to clarify, now that the .dll is there, is it still throwing the error? Sorry for all this, I haven't spent a ton of time figuring out the installer.

Also - careful when you reply - it looks like your signature pulled in some personal details, like phone number and address!

**Comment by EwanSadie** [comment] 2016-01-27 06:46
The dll was there from the start.
I even tried to copy the gShell folder from my working Windows 7 install 
to Windows 10 but I get the same error.
Also tried changing/relax the permission on all the files in the folder.

**Comment by squid808** [comment] 2016-02-03 15:09
Hi Ewan,

I'm not sure what to tell you, I haven't been able to reproduce the issue. Since it sounds like the installer is acting wonky for some reason, the best I can do is this. I've [zipped up all of the files you'll need to run gShell in to a file here](https://goo.gl/5lpef7).

Delete all the files you have in *\Documents\WindowsPowerShell\Modules\gShell*, then replace them with the files from the zip and let me know if that makes any difference.

**Comment by squid808** [comment] 2016-07-20 04:02
Hi @EwanSadie,

Please give the newest version a try. Almost all of the Google dependency files have been directly integrated in to the gShell.dll file, so I'm hoping that will fix it for you. Please let me know.

**Comment by TWillemse** [comment] 2016-08-04 12:53
Testing with the latest version...
Works like a Charm!
Once again... Great job!

**Comment by squid808** [comment] 2016-09-21 04:12
Thanks @TWillemse! Since I haven't heard back from @EwanSadie I'll close this out as stale, or resolved, or both!

**Closed by squid808** 2016-09-21 04:12 UTC
Labels: bug
