### ISSUE TITLE
Loading gshell breaks loading of all additional modules

### ISSUE THREAD

**Issue by jcarterhome** [squid808/gShell#2] opened 2015-03-26 19:09 UTC
I ran across this the other day on my new Windows 8.1 x64 workstation.  I confirmed it on a test system and a vm, all loaded by different people.  v0.0.5.0 and v0.0.6.0 exhibit this behavior.

 - Once the gshell module is loaded, no other module can be loaded.

 - gshell will still work, you just can't load any additional modules.

 - Any modules you load before gshell will work even after you load gshell.

I used the activedirectory module as an example in the output below.  The results were similar on every other module I tried, right up to and including Microsoft.PowerShell.Management.  I'm not a programmer so please let me know what info, if any that I can provide to help resolve this.  Thanks!

Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> import-module gshell
PS C:\WINDOWS\system32> get-aduser
get-aduser : The 'get-aduser' command was found in the module 'ActiveDirectory', but the module could not be loaded.
For more information, run 'Import-Module ActiveDirectory'.
At line:1 char:1
+ get-aduser
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (get-aduser:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

PS C:\WINDOWS\system32> import-module activedirectory
import-module : The following error occurred while loading the extended type data file:
, C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\activedirectory\ActiveDirectory.Types.ps1xml(11) : Error in type
"Microsoft.ActiveDirectory.Management.ADEntity": Exception: Cannot convert the
"Microsoft.ActiveDirectory.Management.ADEntityAdapter" value of type "System.String" to type "System.Type".
...

At line:1 char:1
+ import-module activedirectory
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by squid808** [comment] 2015-05-31 04:21
This seems to be resolved in 0.0.7.0 - can you confirm this? I know you did in the Discussion Group, but I'd like to make it official and put this to bed!

**Comment by squid808** [comment] 2015-07-10 20:36
User reported via email that the issue is no longer around in 0.0.7.0

**Closed by squid808** 2015-07-10 20:36 UTC
Labels: bug
